# This is an example with only required properties:
version: 2
updates:
  # Default branch (master)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
